AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template contains ECS elements

Parameters:

  ResourceTag:
    Description: This value will be used for tagging all resources in the stack
    Type: String
    Default: ecs3tier
    

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
  # Properties: 
  #   CapacityProviders: 
  #     - String
  #   ClusterName: String
  #   ClusterSettings: 
  #     - ClusterSettings
  #   Configuration: 
  #     ClusterConfiguration
  #   DefaultCapacityProviderStrategy: 
  #     - CapacityProviderStrategyItem
  #   Tags: 
  #     - Tag

Outputs:
  ECSCluster:
    Value: !Ref 'ECSCluster'