AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template contains ECS elements

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
  # Properties: 
  #   CapacityProviders: 
  #     - String
  #   ClusterName: String
  #   ClusterSettings: 
  #     - ClusterSettings
  #   Configuration: 
  #     ClusterConfiguration
  #   DefaultCapacityProviderStrategy: 
  #     - CapacityProviderStrategyItem
  #   Tags: 
  #     - Tag

Outputs:
  ECSCluster:
    Value: !Ref 'ECSCluster'