AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template contains IAM elements needed for the whole stack

Parameters:

  ResourceTag:
    Description: This value will be used for tagging all resources in the stack
    Type: String
    Default: ecs3tier

Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ECSServiceRoleName
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com, 
            "ecs-tasks.amazonaws.com",
            "ec2.amazonaws.com"]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 
              - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
              - 'elasticloadbalancing:DeregisterTargets'
              - 'elasticloadbalancing:Describe*'
              - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
              - 'elasticloadbalancing:RegisterTargets'
              - 'ec2:Describe*'
              - 'ec2:AuthorizeSecurityGroupEgress'
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'application-autoscaling:*'
              - 'ecs:CreateCluster'
              - 'ecs:DescribeServices'
              - 'ecs:UpdateService'
              - 'ecs:DeregisterContainerInstance'
              - 'ecs:DiscoverPollEndpoint'
              - 'ecs:Poll'
              - 'ecs:RegisterContainerInstance'
              - 'ecs:StartTelemetrySession'
              - 'ecs:UpdateContainerInstancesState'
              - 'ecs:Submit*'
              - 'ecr:GetAuthorizationToken'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'logs:CreateLogStream'
              - 'logs:DescribeLogStreams'
              - 'logs:PutLogEvents'
              - 'logs:PutRetentionPolicy'
              - 'logs:CreateLogGroup'
              - 'cloudwatch:DescribeAlarms'
              - 'cloudwatch:PutMetricAlarm'
              - 'cloudwatch:DeleteAlarms'
              - 'cloudwatch:DescribeAlarmHistory'
              - 'cloudwatch:DescribeAlarmsForMetric'
              - 'cloudwatch:GetMetricStatistics'
              - 'cloudwatch:ListMetrics'
              - 'cloudwatch:DisableAlarmActions'
              - 'cloudwatch:EnableAlarmActions'
              - 'iam:CreateServiceLinkedRole'
              - 'sns:CreateTopic'
              - 'sns:Subscribe'
              - 'sns:Get*'
              - 'sns:List*'
            Resource: '*'

Outputs:
  ECSServiceRole:
    Value: !Ref ECSServiceRole
    # Export: 
    #   Name: ECSServiceRoleForECS3TierStack