AWSTemplateFormatVersion: 2010-09-09

Description: >
    This template contains IAM elements needed for the whole stack

Parameters:

  ResourceTag:
    Description: This value will be used for tagging all resources in the stack
    Type: String
    Default: ecs3tier

Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['elasticloadbalancing:DeregisterInstancesFromLoadBalancer', 
            'elasticloadbalancing:DeregisterTargets',
            'elasticloadbalancing:Describe*', 
            'elasticloadbalancing:RegisterInstancesWithLoadBalancer',
            'elasticloadbalancing:RegisterTargets', 
            'ec2:Describe*', 
            'ec2:AuthorizeSecurityGroupEgress',
            'ec2:AuthorizeSecurityGroupIngress',
            'application-autoscaling:*',
            'ecs:DescribeServices',
            'ecs:UpdateService',
            'logs:CreateLogStream',
            'logs:DescribeLogStreams',
            'logs:PutRetentionPolicy',
            'logs:CreateLogGroup',
            'cloudwatch:DescribeAlarms',
            'cloudwatch:PutMetricAlarm',
            'cloudwatch:DeleteAlarms',
            'cloudwatch:DescribeAlarmHistory',
            'cloudwatch:DescribeAlarmsForMetric',
            'cloudwatch:GetMetricStatistics',
            'cloudwatch:ListMetrics',
            'cloudwatch:DisableAlarmActions',
            'cloudwatch:EnableAlarmActions',
            'iam:CreateServiceLinkedRole',
            'sns:CreateTopic',
            'sns:Subscribe',
            'sns:Get*',
            'sns:List*'
          ]
            Resource: '*'

Outputs:
  ECSServiceRole:
    Value: !Ref ECSServiceRole
    # Export: 
    #   Name: ECSServiceRoleForECS3TierStack